FROM fedora:latest
LABEL \
    org.opencontainers.image.authors="Pierguido Lambri <plambri@redhat.com>" \
    org.opencontainers.image.licenses=Apache-2.0 \
    purpose="Containers for tests"

RUN yum update -y
RUN yum install -y ansible-core pip git
